# Working Podcast PPO Configuration based on veRL docs
defaults:
  - _self_

# Run configuration
run:
  output_dir: runs/podcast_ppo_working_test
  total_steps: 5
  eval_interval: 2
  save_interval: 10
  resume_from: null

# Data configuration
data:
  tokenizer: null
  train_files: data/podcast_questions_verl_format.parquet
  val_files: data/podcast_questions_verl_format.parquet
  prompt_key: prompt
  reward_fn_key: data_source
  max_prompt_length: 256
  max_response_length: 128
  train_batch_size: 8
  val_batch_size: null
  return_raw_input_ids: false
  return_raw_chat: false
  return_full_prompt: false
  shuffle: true
  filter_overlong_prompts: false
  truncation: error
  trust_remote_code: true

# Actor rollout configuration
actor_rollout_ref:
  hybrid_engine: true
  model:
    path: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    external_lib: null
    override_config: {}
    enable_gradient_checkpointing: true
    enable_activation_offload: false
    trust_remote_code: true
    use_remove_padding: false
    
  actor:
    strategy: fsdp
    ppo_mini_batch_size: 8
    ppo_micro_batch_size: null
    ppo_micro_batch_size_per_gpu: 1
    use_dynamic_bsz: false
    ppo_max_token_len_per_gpu: 384
    grad_clip: 1.0
    clip_ratio: 0.2
    clip_ratio_low: 0.2
    clip_ratio_high: 0.2
    entropy_coeff: 0.01
    use_kl_loss: false
    use_torch_compile: false
    ppo_epochs: 1
    data_loader_seed: 42
    shuffle: false
    loss_agg_mode: "seq-mean-token-mean"
    ulysses_sequence_parallel_size: 1
    
    optim:
      lr: 1e-5
      lr_warmup_steps: 1
      lr_warmup_steps_ratio: 0.0
      min_lr_ratio: 0.0
      num_cycles: 0.5
      warmup_style: constant
      total_training_steps: 5
      
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: false
      optimizer_offload: false
      fsdp_size: -1
      
    checkpoint:
      contents: ['model', 'optimizer', 'extra']
      
  ref:
    fsdp_config:
      param_offload: false
      wrap_policy:
        min_num_params: 0
    log_prob_micro_batch_size: null
    log_prob_micro_batch_size_per_gpu: 1
    log_prob_use_dynamic_bsz: false
    log_prob_max_token_len_per_gpu: 384
    ulysses_sequence_parallel_size: 1
    
  rollout:
    name: sglang
    mode: sync
    temperature: 0.7
    top_p: 0.95
    prompt_length: 256
    response_length: 128
    dtype: bfloat16
    gpu_memory_utilization: 0.3
    ignore_eos: false
    enforce_eager: true
    free_cache_engine: true
    do_sample: true
    load_format: dummy_dtensor
    log_prob_micro_batch_size: null
    log_prob_micro_batch_size_per_gpu: 1
    log_prob_use_dynamic_bsz: false
    log_prob_max_token_len_per_gpu: 384
    tensor_model_parallel_size: 4
    max_num_batched_tokens: 2048
    max_num_seqs: 256
    engine_kwargs:
      sglang:
        attention_backend: null
    n: 1
    val_kwargs:
      top_p: 1.0
      temperature: 0
      n: 1
      do_sample: false
    multi_turn:
      enable: false
      tool_config_path: null

# Critic configuration
critic:
  rollout_n: 1
  strategy: fsdp
  ppo_mini_batch_size: 8
  ppo_micro_batch_size: null
  ppo_micro_batch_size_per_gpu: 1
  use_dynamic_bsz: false
  ppo_max_token_len_per_gpu: 384
  forward_micro_batch_size_per_gpu: 1
  forward_max_token_len_per_gpu: 384
  ppo_epochs: 1
  data_loader_seed: 42
  shuffle: false
  loss_agg_mode: "seq-mean-token-mean"
  ulysses_sequence_parallel_size: 1
  grad_clip: 1.0
  use_torch_compile: false
  cliprange_value: 0.5
  model:
    path: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    tokenizer_path: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    external_lib: null
    override_config: {}
    enable_gradient_checkpointing: true
    use_remove_padding: false
    trust_remote_code: true
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: false
      optimizer_offload: false
      fsdp_size: -1
  optim:
    lr: 5e-6
    lr_warmup_steps: 1
    lr_warmup_steps_ratio: 0.0
    total_training_steps: 5
  fsdp_config:
    wrap_policy:
      min_num_params: 0
    param_offload: false
    optimizer_offload: false
  checkpoint:
    contents: ['model', 'optimizer', 'extra']

# Reward model configuration - DISABLED (using custom reward function instead)
reward_model:
  enable: false
  launch_reward_fn_async: false

# Custom reward function
custom_reward_function:
  path: podcast_reward.py
  name: compute_score
  use_local_judge: false
  judge_url: null

# Algorithm configuration
algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: gae
  use_kl_in_reward: false
  use_pf_ppo: false
  pf_ppo:
    reweight_method: null
    weight_pow: 1.0
  kl_penalty: kl
  kl_ctrl:
    type: fixed
    kl_coef: 0.01
    horizon: 10000
    target_kl: 0.1

# Ray configuration
ray_init:
  address: null
  num_cpus: null
  num_gpus: null
  object_store_memory: null
  
# Trainer configuration  
trainer:
  total_epochs: 1
  total_training_steps: null
  project_name: verl_simple_test
  experiment_name: podcast_simple_test
  logger: ['console']
  nnodes: 1
  n_gpus_per_node: 8
  device: cuda
  save_freq: -1
  val_before_train: false
  test_freq: 5
  critic_warmup: 0
  default_hdfs_dir: null
  default_local_dir: checkpoints/verl_simple_test
  resume_mode: disable 
  balance_batch: true
  log_val_generations: 0 